### PR TITLE
Fixes formatting for nvme or disks that ends in a number

### LINKED ISSUE #42: Error formating partition when disk is nvme
Error when formating a partition on NVME disks since the device partition naming changes. 

```
[root@snonode ~]# podman run -v /dev:/dev -v /mnt:/mnt -v /root/.docker:/root/.docker --privileged -it --rm quay.io/alosadag/telco-ran-tools:pr41 -- factory-precaching-cli partition -d /dev/nvme0n1 -s 100

error: unable to format device: Error accessing specified device /dev/nvme0n11: No such file or directory
Usage: mkfs.xfs
/* blocksize */		[-b size=num]
/* metadata */		[-m crc=0|1,finobt=0|1,uuid=xxx,rmapbt=0|1,reflink=0|1,
			    inobtcount=0|1,bigtime=0|1]
/* data subvol */	[-d agcount=n,agsize=n,file,name=xxx,size=num,
			    (sunit=value,swidth=value|su=num,sw=num|noalign),
			    sectsize=num
/* force overwrite */	[-f]
/* inode size */	[-i log=n|perblock=n|size=num,maxpct=n,attr=0|1|2,
			    projid32bit=0|1,sparse=0|1]
/* no discard */	[-K]
/* log subvol */	[-l agnum=n,internal,size=num,logdev=xxx,version=n
			    sunit=value|su=num,sectsize=num,lazy-count=0|1]
/* label */		[-L label (maximum 12 characters)]
/* naming */		[-n size=num,version=2|ci,ftype=0|1]
/* no-op info only */	[-N]
/* prototype file */	[-p fname]
/* quiet */		[-q]
/* realtime subvol */	[-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */	[-s size=num]
/* version */		[-V]
			devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).
```
The error is that partition for nvme ends with p1 instead of 1 (sda1 for instance).

The partition is created, but the partition is not formated in xfs as expected.

### PR DESCRIPTION
**Pull request by alosadagrande**
This code fixes the problem when formatting disks that end with a number instead of a string. In those cases, a 'p' + the number of the partition needs to be added to know what partition needs to be formatted after being parted.

Fixes #42 
Signed-off-by: Alberto Losada <alosadag@redhat.com>

### CODE REVIEW

File: cmd/partition.go [hunk 1]
```diff
@@ -8,6 +8,7 @@ import (
 	"fmt"
 	"os"
 	"os/exec"
+  "strconv"
```
Comment (donpenney) [inline cmd/partition.go:11]: Please run "go fmt ..." to fix up the formatting ... I'll add this as a pre-build step in the Makefile in a future update

**Review by donpenney — CHANGES_REQUESTED** [review]

**Review by donpenney — APPROVED** [review]
/lgtm
